# Generated by Django 4.0.6 on 2022-07-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationary', 'stationary'), ('Electronics', 'Electronics'), ('Food', 'Food')], max_length=20),
        ),
    ]
